import { ComponentBars } from '@/components/ComponentBars'
import { Recommendations } from '@/components/Recommendations'
import { ScoreGauge } from '@/components/ScoreGauge'
import { SectionChecklist } from '@/components/SectionChecklist'
import { SkillBadges } from '@/components/SkillBadges'
import type { AnalysisResponse } from '@/lib/api'

/** The full results view. Shared by /analyze and /results/:id. */
export function AnalysisReport({
  result,
  divider = false,
}: {
  result: AnalysisResponse
  divider?: boolean
}) {
  return (
      <div
        className={`space-y-6 ${
          divider ? 'border-t border-slate-200 pt-8 dark:border-slate-800' : ''
        }`}
      >
        <h2 className="text-xl font-semibold tracking-tight">
          {result.job_title || 'Results'}
          <span className="ml-2 text-sm font-normal text-slate-500 dark:text-slate-400">
            {result.resume_filename}
          </span>
        </h2>

        {/* ---- score overview ---- */}
        <div className="grid gap-4 lg:grid-cols-5">
          <div className="surface p-5 lg:col-span-2">
            <ScoreGauge score={result.match_score} />
          </div>
          <div className="surface p-5 lg:col-span-3">
            <h3 className="mb-3 text-sm font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Score breakdown
            </h3>
            <ComponentBars result={result} />
          </div>
        </div>

        {/* ---- skills ---- */}
        <div className="grid gap-4 lg:grid-cols-2">
          <section className="surface p-5">
            <h3 className="mb-4 text-sm font-semibold uppercase tracking-wider text-emerald-600 dark:text-emerald-400">
              Matched skills ({result.matched_skills.length})
            </h3>
            <SkillBadges skills={result.matched_skills} />
          </section>

          <section className="surface p-5">
            <h3 className="mb-4 text-sm font-semibold uppercase tracking-wider text-rose-600 dark:text-rose-400">
              Missing skills ({result.missing_skills.length})
            </h3>
            {result.missing_skills.length === 0 ? (
              <p className="text-sm text-slate-500 dark:text-slate-400">
                Nothing missing — the resume names every skill the job asked for.
              </p>
            ) : (
              <SkillBadges skills={result.missing_skills} />
            )}
          </section>
        </div>

        {/* ---- keywords + structure ---- */}
        <div className="grid gap-4 lg:grid-cols-2">
          <section className="surface p-5">
            <h3 className="mb-4 text-sm font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Important keywords
            </h3>
            <div className="flex flex-wrap gap-1.5">
              {result.keywords.map((k) => (
                <span
                  key={k.term}
                  className={`rounded-md px-2 py-1 font-mono text-xs ${
                    k.found
                      ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300'
                      : 'bg-rose-50 text-rose-700 dark:bg-rose-500/10 dark:text-rose-300'
                  }`}
                >
                  {k.found ? '✓' : '✗'} {k.term}
                </span>
              ))}
            </div>
          </section>

          <section className="surface p-5">
            <h3 className="mb-4 text-sm font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Resume structure
            </h3>
            <SectionChecklist sections={result.sections} />
          </section>
        </div>

        {/* ---- recommendations ---- */}
        <section className="surface p-5">
          <h3 className="mb-4 text-sm font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            Recommendations
          </h3>
          <Recommendations items={result.recommendations} />
          <p className="mt-5 border-t border-slate-100 pt-3 text-xs text-slate-500 dark:border-slate-800 dark:text-slate-500">
            Generated by deterministic rules, not a language model. The same
            resume and posting always produce the same suggestions.
          </p>
        </section>
      </div>
  )
}
