"""add semantic_similarity to analyses

Revision ID: 5fc7ef1b791c
Revises: d727d963823f
Create Date: 2026-08-22 16:07:38.305408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5fc7ef1b791c'
down_revision: Union[str, Sequence[str], None] = 'd727d963823f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('semantic_similarity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'semantic_similarity')
    # ### end Alembic commands ###
