"""store credential match details

Revision ID: a67dd7f30fe2
Revises: e282a307172d
Create Date: 2026-09-03 17:30:37.963152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67dd7f30fe2'
down_revision: Union[str, Sequence[str], None] = 'e282a307172d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows predate these, so add nullable, backfill, then enforce.
    op.add_column("analyses", sa.Column("experience_detail", sa.String(200), nullable=True))
    op.add_column("analyses", sa.Column("education_detail", sa.String(200), nullable=True))
    op.execute("UPDATE analyses SET experience_detail = '', education_detail = ''")
    op.alter_column("analyses", "experience_detail",
                    existing_type=sa.String(200), nullable=False)
    op.alter_column("analyses", "education_detail",
                    existing_type=sa.String(200), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'education_detail')
    op.drop_column('analyses', 'experience_detail')
    # ### end Alembic commands ###
