"""add jd intelligence and partial skills

Revision ID: b296d32b1782
Revises: 5fc7ef1b791c
Create Date: 2026-08-30 19:16:09.603784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b296d32b1782'
down_revision: Union[str, Sequence[str], None] = '5fc7ef1b791c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # MySQL rejects a literal DEFAULT on a JSON column, so NOT NULL columns are
    # added in three steps: add nullable, backfill existing rows, then enforce.
    op.add_column("analyses", sa.Column("partial_skills", sa.JSON(), nullable=True))
    op.add_column("job_descriptions", sa.Column("company", sa.String(160), nullable=True))
    op.add_column("job_descriptions", sa.Column("role", sa.String(160), nullable=True))
    op.add_column("job_descriptions", sa.Column("parsed", sa.JSON(), nullable=True))

    # Rows analysed before this migration simply had no partial matches.
    op.execute("UPDATE analyses SET partial_skills = JSON_ARRAY()")
    op.execute("UPDATE job_descriptions SET company = '', role = '', parsed = JSON_OBJECT()")

    op.alter_column("analyses", "partial_skills", existing_type=sa.JSON(), nullable=False)
    op.alter_column("job_descriptions", "company",
                    existing_type=sa.String(160), nullable=False)
    op.alter_column("job_descriptions", "role",
                    existing_type=sa.String(160), nullable=False)
    op.alter_column("job_descriptions", "parsed", existing_type=sa.JSON(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'parsed')
    op.drop_column('job_descriptions', 'role')
    op.drop_column('job_descriptions', 'company')
    op.drop_column('analyses', 'partial_skills')
    # ### end Alembic commands ###
