"""add resume quality score to analyses

Revision ID: b7fa3b8d2767
Revises: b296d32b1782
Create Date: 2026-09-03 17:02:34.183439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fa3b8d2767'
down_revision: Union[str, Sequence[str], None] = 'b296d32b1782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # resume_quality_score stays nullable: analyses created before this feature
    # existed genuinely have no value, and 0 would read as "a terrible resume".
    op.add_column("analyses", sa.Column("resume_quality_score", sa.Float(), nullable=True))

    # JSON cannot take a literal DEFAULT in MySQL: add nullable, backfill, enforce.
    op.add_column("analyses", sa.Column("quality_breakdown", sa.JSON(), nullable=True))
    op.execute("UPDATE analyses SET quality_breakdown = JSON_ARRAY()")
    op.alter_column("analyses", "quality_breakdown", existing_type=sa.JSON(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'quality_breakdown')
    op.drop_column('analyses', 'resume_quality_score')
    # ### end Alembic commands ###
