"""create job_descriptions and analyses, add resume version

Revision ID: d727d963823f
Revises: 904f3e9e4f81
Create Date: 2026-08-22 15:35:09.944124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd727d963823f'
down_revision: Union[str, Sequence[str], None] = '904f3e9e4f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(length=4294967295), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_index('ix_jobs_user_hash', 'job_descriptions', ['user_id', 'content_hash'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('job_description_id', sa.Integer(), nullable=True),
    sa.Column('resume_filename', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('text_similarity', sa.Float(), nullable=False),
    sa.Column('skill_match', sa.Float(), nullable=True),
    sa.Column('keyword_match', sa.Float(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('extra_skills', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_user_created', 'analyses', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    # server_default so existing rows get version 1 rather than failing NOT NULL.
    op.add_column(
        'resumes', sa.Column('version', sa.Integer(), nullable=False, server_default='1')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'version')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_index('ix_analyses_user_created', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index('ix_jobs_user_hash', table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
