"""add experience education match and blockers

Revision ID: e282a307172d
Revises: b7fa3b8d2767
Create Date: 2026-09-03 17:25:48.008773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e282a307172d'
down_revision: Union[str, Sequence[str], None] = 'b7fa3b8d2767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Both stay nullable: a posting that states no requirement genuinely has
    # no score for these, and 0 would read as "you failed the requirement".
    op.add_column("analyses", sa.Column("experience_match", sa.Float(), nullable=True))
    op.add_column("analyses", sa.Column("education_match", sa.Float(), nullable=True))

    # JSON cannot take a literal DEFAULT in MySQL: add nullable, backfill, enforce.
    op.add_column("analyses", sa.Column("blockers", sa.JSON(), nullable=True))
    op.execute("UPDATE analyses SET blockers = JSON_ARRAY()")
    op.alter_column("analyses", "blockers", existing_type=sa.JSON(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'blockers')
    op.drop_column('analyses', 'education_match')
    op.drop_column('analyses', 'experience_match')
    # ### end Alembic commands ###
